blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/Stegripe/Pempek/discussions/new?category=feature-requests
    about: Suggest an idea for Pempek
  - name: Exploit Report
    url: https://stegripe.org/discord
    about: |
      Since GitHub does not allow private issues, exploit reports are currently handled through our Discord.
      To report an exploit, contact a moderator on the Pempek Discord.
  - name: Pempek Discord
    url: https://stegripe.org/discord
    about: If you are having issues with Spark profiling or have other minor issues, come join our Discord server for help!
