name: Pempek-Test-Plugin
version: ${version}
main: org.stegripe.testplugin.TestPlugin
description: Pempek Test Plugin
author: Stegripe
api-version: ${apiversion}
load: STARTUP
#bootstrapper: org.stegripe.testplugin.TestPluginBootstrap
#loader: org.stegripe.testplugin.TestPluginLoader
defaultPerm: FALSE
permissions:
dependencies:
